spring:
  datasource:
    username: weiyu
    password: '0000'
    url: jdbc:mysql://149.28.126.51:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5tPBG3ur4kNADjhaADcK
      secret-key: 6jZ2WMO3uod2DSRgXfA2L16gjKgRtm
      oss:
        endpoint: https://oss-us-west-1.aliyuncs.com
  application:
    name: mall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: America/Winnipeg

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config: # the rule of logic deletion
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000
  servlet:
    context-path: /mall
logging:
  level:
    com.product: debug
